name: CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build

    - name: Build Docker images
      run: docker compose build

    # 🔐 Login Docker Hub
    - name: Login Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 🏷️ Tag images
    - name: Tag images
      run: |
        docker tag simpleprojectdeploy-web ${{ secrets.DOCKER_USERNAME }}/simpleprojectdeploy-web:latest
        docker tag simpleprojectdeploy-api ${{ secrets.DOCKER_USERNAME }}/simpleprojectdeploy-api:latest

    # 🚀 Push images
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/simpleprojectdeploy-web:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/simpleprojectdeploy-api:latest

    # 🔁 Trigger Render Deploy (auto-deploy)
    - name: Deploy API to Render
      run: curl -X POST ${{ secrets.RENDER_HOOK_API }}

    - name: Deploy Web to Render
      run: curl -X POST ${{ secrets.RENDER_HOOK_WEB }}